apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  generation: 1
  name: letsencrypt-prod
spec:
  acme:
    email: anhttok@gmail.com
    privateKeySecretRef:
      name: letsencrypt-secret-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx"