services:
  mediasoup:
    image: docker.io/damienh/mediasoup:v1.4
    environment:
      - PROTOO_LISTEN_PORT=4443
      - MEDIASOUP_MIN_PORT=40000
      - MEDIASOUP_MAX_PORT=49999
      - HTTPS_CERT_FULLCHAIN="/service/certs/fullchain.pem"
      - HTTPS_CERT_PRIVKEY="/service/certs/privkey.pem"
    ports:
      - '4443:4443'
  coturn:
    image: coturn/coturn
    command: -n --log-file=stdout --lt-cred-mech --fingerprint --no-multicast-peers --no-cli --no-tlsv1 --no-tlsv1_1 --realm=my.realm.org --user user:pass -v
    ports:
      - "3478:3478/udp"
